apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: adservice
        image: 183631308419.dkr.ecr.us-east-1.amazonaws.com/adservice:6
        ports:
        - containerPort: 80

